# Generated by Django 3.1.3 on 2020-11-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.ImageField(upload_to='images'),
        ),
    ]
