# Generated by Django 3.1.3 on 2020-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20201112_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.FileField(upload_to='images'),
        ),
    ]
